name: dio_cache_interceptor_hive_store
description: A DB cache store implementation with Hive for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_hive_store
version: 3.2.2

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  dio_cache_interceptor:
    git:
      url: https://github.com/jeetmotilaloswal/dio_cache_interceptor.git
      path: dio_cache_interceptor
      ref: master_cache
  # https://pub.dev/packages/hive
  hive: ^2.0.5

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^3.0.0
  # https://pub.dev/packages/test
  test: ^1.23.1
